### ISSUE TITLE
Was the filtrate function removed from ncdump?

### ISSUE THREAD

**Issue by RMORSEcode** [mdsumner/angstroms#7]
The changes you made corrected the problems I had with raster (THANK YOU!), but now I can't seem to find a function and am getting an error on `activate` 
Did `filtrate` become `hyper_filter` in ncdump?

https://github.com/hypertidy/angstroms/blob/master/inst/couple-Atlantis/cpolar_coupling_2.R
from line 216:

`library(ncdump)`
`library(dplyr)`
`ncfile <- "~/Git/shinyrAtlantis/egfiles/SOtempdummy.nc"`
`con <- ncdf4::nc_open(ncfile)`
`trans <- ncdump::NetCDF(ncfile) %>% activate("temperature") %>% filtrate() `
`hslab <- bind_rows(lapply(trans, function(x) tibble(name = x$name[1], start = min(x$step), count =length(x$step))))`
`slab <- ncdf4::ncvar_get(con, "temperature", 
                         start = hslab$start, 
                         count = hslab$count)`
`temp <- as_tib_slab(trans, slab, activ = "temperature")`

Here is the error:
`trans <- ncdump::NetCDF(ncfile) %>% activate("temperature") %>% filtrate() `
Error in filtrate(.) : could not find function "filtrate"
In addition: Warning message:
In `active<-.default`(`*tmp*`, value = what) :
  activating as a default, this object not recognized as activatable

**Comment by mdsumner** [comment]
Ah yes, this has completely changed - filtrate was a very early stab at having axis-transforms, and that became hyper_filter in tidync - and recently that changed again so that there's really on one class. 

I'll update that example script! -  this has languished and just isn't properly fleshed out.

**Comment by RMORSEcode** [comment]
Thanks!

**Comment by mdsumner** [comment]
Ok, please ignore `cpolar_coupling_2.R` - that was a premature attempt to move to tidync/sf combination. `cpolar_coupling_z_index.R` is more straightforward and should work, but still with the caveat that it's an ongoing work-in-progress for me.
